### PR TITLE
Browserify-specific fix for #29

### PR DESCRIPTION
**Pull request by aickin**
Fix for #29, trying to optimize browserify modules, in a very specific way.

This fix will optimize function expressions that are:
- an element of an array,
- which in turn is a value of an object literal,
- which has a numeric name in the object literal,
- where the object literal is an argument to a function call,
- and the function call is an IIFE.

Added both positive and negative test cases. I did some basic testing against the PouchDB benchmark, and this PR makes it a lot faster.

### CODE REVIEW

**Comment by nolanlawson** [comment]
This looks fantastic! One thing I was momentarily confused on was:

>  browserify-style function call that has non-numeric object indices shouldn't be optimized

I thought this referred to Browserify with the `bundle-collapser` plugin vs without, but I tested manually and confirmed that both `bundle-collapser` style and regular style are covered (i.e. parens are correctly added). I'll add some additional tests on the way in to make this clearer.

BTW just a quick remark that these PRs are incredibly thorough and well-written, and I'm extremely grateful that you're improving my little weekend project so much. 🙇  optimize-js is suddenly turning into a very nice general-purpose tool!

**Comment by aickin** [comment]
> BTW just a quick remark that these PRs are incredibly thorough and well-written

Aw shucks, my pleasure. Thanks for accepting the PRs!

**Comment by nki2** [comment]
It seems this update is not included in the release v1.0.2 yet. (not avail via npm neither)
Could you please check (and make it available if possible)
Thank you!

**Comment by nolanlawson** [comment]
I'm going to work on a large rewrite of the benchmarks to include better stats, and then re-run them to ensure there are no regressions. Unfortunately I've been swamped, hence why this has sat for so long.

**Pull request merged**
