### PR TITLE
Add area for 3rd party plugins

### PR DESCRIPTION
**Pull request by sergejmueller**

### CODE REVIEW

**Comment by nolanlawson** [comment]
Let's add the Gulp one too: https://github.com/prateekbh/gulp-optimize-js

**Comment by nolanlawson** [comment]
Thanks for the PR; merging!

**Comment by vigneshshanmugam** [comment]
:(  @nolanlawson https://github.com/vigneshshanmugam/optimize-js-plugin

**Comment by nolanlawson** [comment]
@vigneshshanmugam PRs welcome! :)

**Pull request merged**
